### PR TITLE
adding support for the ec2 protocol

### PR DESCRIPTION
**Pull request by cheese-head**
These changes would allow for support of the ec2 protocol. There's also a pending pull request in the aws-codegen repo that would need to be approved. https://github.com/aws-beam/aws-codegen/pull/100

### CODE REVIEW

**Comment by onno-vos-dev** [comment]
Will review later during the day but letting pipelines run in the meantime 👌 Thank you for the PR's already! <3

**Comment by onno-vos-dev** [comment]
Rebased on latest master due to your previous build not compiling since `inspector_scan.ex` generated warnings since there were no operations on it.

**Comment by onno-vos-dev** [comment]
I apologise for the delay on both this PR as well as https://github.com/aws-beam/aws-codegen/pull/100. Private life got in the way 😢 

Took care of everything now and will try to roll out a new release tomorrow 👌

**Comment by cheese-head** [comment]
@onno-vos-dev Any chance you can have a new release pushed to hex for these changes? Thanks!

**Comment by onno-vos-dev** [comment]
@cheese-head Sorry I totally missed this one. All other aws-beam repos have on-merge-release pipelines setup so I forgot about this one 😢 

On it! Will ping you in about 20-30 minutes!

**Comment by onno-vos-dev** [comment]
@cheese-head https://hex.pm/packages/aws/0.14.0 Done! 🎉

**Pull request merged**
