### PR TITLE
Regenerate code to upgrade to Go AWS SDK v1.25.14

### PR DESCRIPTION
**Pull request by jcomellas**
I've regenerated the code for the Elixir library using a modified version of aws-codegen with the changes in this PR: aws-beam/aws-codegen#5. The changes include:

* Replace calls to any function that had been deprecated up to Elixir 1.9
* Upgrade dependencies to their latest version
* Regenerate code based on Go AWS SDK v1.25.14.

### CODE REVIEW

**Comment by jcomellas** [comment]
@tsantero This might be of interest to you.

**Comment by jfacorro** [comment]
Would it be possible to merge this PR? 

The changes in `aws-codegen` have been merged already through [this PR](https://github.com/aws-beam/aws-codegen/pull/5), which makes this out-of-sync with the code generated by it. 😢  

@tsantero @mrallen This project seems quite useful and I would be happy to be added as a collaborator to get it into a better shape. 

In particular I would like to:

* Publish the latest versions of the `aws-elixir` and `aws-erlang` libraries to hex.pm.
* Add Erlang support for the rest_json template.
* Include some missing APIs like SNS and SQS.

**Comment by jcomellas** [comment]
@jfacorro @mrallen1 FYI, we've been using the code in this PR in a project with @tsantero without issues for several months already.

**Comment by jfacorro** [comment]
That's pretty neat. Does @tsantero have permissions to merge the PR then?

**Comment by jcomellas** [comment]
> That's pretty neat. Does @tsantero have permissions to merge the PR then?

@jfacorro From what he told me, he was waiting for @mrallen1 to merge it. I'll ask him again today.

**Comment by tsantero** [comment]
@jfacorro @jcomellas I can merge, but I cannot publish a new package to hex.

**Comment by jfacorro** [comment]
> but I cannot publish a new package to hex.

Is it because there is already an existing one [here](https://hex.pm/packages/aws)?

**Comment by tsantero** [comment]
no, i simply lack hex credentials for this package.

**Comment by jfacorro** [comment]
I understand. We can maybe solve publishing the hex package later. Could we merge this PR in the meantime? 😄 

@tsantero I would like to contribute to the projects in the `aws-beam` organisation by adding support to additional AWS APIs in both Erlang and Elixir. For example I've been working on adding rest_json support for Erlang in this [branch](https://github.com/aws-beam/aws-codegen/compare/master...jfacorro:erlang-rest_json-spec-template?expand=1).

I'm really interested in improving these projects and I'm willing to invest some work in doing so. To make this work more dynamic would it be possible to include me in the `aws-beam` organization?

**Comment by mrallen1** [comment]
@jfacorro welcome to the team

**Comment by mrallen1** [comment]
As far as publishing to hex, just give me your hex usernames and ill add you to the owner list for the packages.

**Comment by jfacorro** [comment]
> Welcome to the team

Thank you! 😄 

> As far as publishing to hex, just give me your hex usernames and ill add you to the owner list for the packages.

My hex username is `jfacorro`. If you need any other information please let me know.

**Comment by jfacorro** [comment]
@mrallen1 Sorry to bother you again but even though I'm a member of the organization I don't seem to have access to much. 

I noticed this while I was attempting to close issue #7 which looks like there is not much to do.

**Comment by mrallen1** [comment]
Yeah sorry, that's pretty lame. I think it should be fixed now.

**Comment by mrallen1** [comment]
@jfacorro I added you to the owners list on the `aws` package on hex

**Comment by jfacorro** [comment]
@mrallen1 Thank you for your trust and help. 😄

**Comment by mrallen1** [comment]
No no, thank **you** for getting this stuff done. tbh I really don't have a lot of time for this rn.

**Comment by jkakar** [comment]
Yay, thank you @jfacorro!

**Pull request merged**
