### PR TITLE
:memo: [doc] Added example for s3 textract

### PR DESCRIPTION
**Pull request by enkr1**
I was struggling when using the library and I hope this simple example helps somebody in the future.

Best wishes, 
Jing Hui P.

### CODE REVIEW

**Comment by onno-vos-dev** [comment]
I'm not sure what would be a good home for it but the generated code is not the place at least. Tonight, this file will be re-generated so even if we were to merge this, it'd be lost the night after. 

May I consider either a `EXAMPLES.md` or an `examples/textract.ex` file to be added instead? :-)

**Comment by enkr1** [comment]
> Thank you for the PR!
> 
> I'm not sure what would be a good home for it but the generated code is not the place at least. Tonight, this file will be re-generated so even if we were to merge this, it'd be lost the night after.
> 
> May I consider either a `EXAMPLES.md` or an `examples/textract.ex` file to be added instead? :-)

Hi @onno-vos-dev, would `EXAMPLES.md` or `./examples/textract.ex` would be shown on the hexdocs documentation page?

**Comment by onno-vos-dev** [comment]
Rebased on latest `master` just to make sure the CI still passes. Locally it works just fine but want the CI to agree with me prior to merging! 

I'm really sorry for the delay 🤐

**Comment by onno-vos-dev** [comment]
@enkr1 `examples/*` do not get published to hexdocs but I'll open an issue to look into that. Having it be part of the repo is a good start at least IMHO👌

**Pull request merged**
